language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - develop
    - /^v[\d]+\.[\d]+\.[\d]+$/
deploy:
  provider: npm
  email: me@jacobmoretti.com
  api_key:
    secure: vKWDylM8DTyrc+cBuNZBuThgBA2ffHCktrxyNsG0u7MMPDy9xwNq1kAkBl/besiG5f5Gwp5ZRnMZ7XGWzhAZbsuexOC8Do2FXhdQ7VqTuCCzT6CDa6MBnl7arfg1tb5yFVdNvDqd9q6SvP6UxMGCSI//DwUxk6vXPPFUTsNILGcDtn9Lck4ALYaMR3zURCXV+0jRLvZ166ctbu84SvJMZnugRnWiYpgS/nkJ4i2B5JVX2lnd55JiE0OX7/sGPTHN6LGpRWrJu/9KOwiAlH/SxLi1vubMpcEqk6b7OUrnYk6+QWIXHLUwf8Q2a1VaZG8nziosJHN2VR9bSebvQgGfJTkZ6ZRlf7jgZFXq6YMv7HquEbwUTbeHQXRpF42+NI73Q5ZrVwYWh7yYiWnNg2dvqR/WlMTBhWaGjGs4HnWoP8GzLwbowElst8BXFsElhTdoelapDM7u3wrvqnSPC2ZkqGlY0dsWTW/XD64gqrIyIBjH48yMGKPL6lor6ZwQzTQFfrKY5rqzrVKPVNHb8QQ9l4FRiJZrQQeCEEaNcW7LWJI4ecyYfxoHKUP+SF9MDVa/EuLQLe748dVAbwf18o6kSYv7JwL/bEQTORhz+kj22UA7Btz84vgU2hRLOLUbDOpaYhAtQkbw20+8eWAXIHZcwcdCGp/6WJNOwDAgbwXK8Bg=
  on:
    tags: true
    repo: TrueCar/react-launch-darkly
  skip_cleanup: true
