language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - develop
    - /^v[\d]+\.[\d]+\.[\d]+$/
deploy:
  provider: npm
  email: me@jacobmoretti.com
  api_key: BG2rF60TUHlcSnGrqXwvHs0vSXN5SuH0+T8KkhTW4gSG2uD0ddEB4IGsqNbl0vp2pg8lHAAEKtZpKlks4vcDVNru84YBP2MYMdGV1CS+LRY+nqd2PgC3WY4rCC1D3yhut2oHuDL7CiD6tEml/nEkzig+G0KigqnEHiMj02vlB80xQ+CaFXkIsb3kQE6s0jlKwc824YliQAe5Ud1usjss444ymFyf6NrMHfiK05n/8O51uDwtJYWvWgZ2b7FGzn2815Mvce7f9eU8+xiMD+6fVpDlR5Hn1h0/QlViNDoug71KW4U9HUFMalwZH/kUtPwSaZyZvFxdaRmV9D5QFVyXiKxdxtBbx56wRc+JbVXr1PQZ4OXbfighKgQ5wgGxoCTsLR0naVifGgJgATy7UNBlGkYjN8HffvgSFSAUrI7L9CrvC8mJd3o1jFqNDYadaiBPgHKKOLKBvRbE9DpgpgmnEC46k/T2pMa1lbpczQcQV8MknNaHMrgDP3C+YLnKpBXF65UQBa5rIiPwpiWRIh8NjqZn5vVjC0Wckg+UnxS24FcnzYtGmEEMI/JBJD2caynjzJAbl/sbPLqBA4qwFIQqZgxrP0hA1/XtEotfc495oBo03Qsf+1ZboCzqwEAwbWyI8pmC8ZD8d3jlkDzptTYsq6kwPTipcYohoSJF9r+WbFs=
  on:
    tags: true
    repo: TrueCar/react-launch-darkly
  skip_cleanup: true
