language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - develop
    - /^v[\d]+\.[\d]+\.[\d]+$/
deploy:
  provider: npm
  email: me@jacobmoretti.com
  api_key:
    secure: V4UeHcv2unVcxPyBNoQ3nktCRudmzlYwg0CfxZt66n6WhkpH3HyC7nkhp4rIPfb6lXGPkvvB5dcE5+WT58oAVw/IilhUDUr+ygy9sDSBQcbEpUqCfwMuqLXeF6XbJcDiCEdmFJ5xXZiC5y8+TY75pyB7ZZGrtcyvFrfPlhiXpkYW3hOUH1zhRIRNRgpL2yH4qL/v+1hiHYjRpKlVs8ZbfRWnwwRqibRO/q7EWkC4/h3lT8N38U99/d8En5tP5Dl5fJGjX7+890zDt0+2XeDxxUm3zrOlgOtWA9ShbOW58wT+XuW8k4PX3eRbsTAez0WepZnY4lMjh+2qxdLM4eW1l5reQXyYtK5OCTSRWKDVuTVk2TbVk3MOC0/rzIuZRcA5W/fI0Jo5zkFpoD+QUCjliJUcfEfwxo1EutayWG3CHRUib6WU2zt+dxSYUpqse/JXDpYCYF9Bt+aHFsok3X1tyVfjldWKHLfpfDfkE2X5Ekw5HpN0Q/vMYqRaRScWmcOYgarsKhl+AzbfeTnerze+PptooKQemGLLTaGNMeyrxUME4YWfQTMgzjgp4Jdc0qBpRFlei0cIG2ktJTtsplWOQpLOx/9xT8CUoyRrpwoy1IBK1GW/pR5cmONtIIpBQ0Ct+S3fMymQ1LQasmR9C79acLGuGcnmMAS8Lf8bjErsPc4=
  on:
    tags: true
    repo: TrueCar/react-launch-darkly
  skip_cleanup: true
